version: '3.5'
networks:
  tests-network:
    driver: bridge
    name: tests-network
services:
  user-service:
    container_name: user-service
    build:
      context: user-service
      dockerfile: Dockerfile
    image: pranaysinghdev/user-service:latest
    networks: [tests-network]
    ports:
      - 5000:5000
    env_file:
      - compose.env
  product-service:
    container_name: product-service
    build:
      context: product-service
      dockerfile: Dockerfile
    image: pranaysinghdev/product-service:latest
    networks: [tests-network]
    ports:
      - 5001:5001
    env_file:
      - compose.env