version: '3.5'
networks:
  tests-network:
    driver: bridge
    name: tests-network
services:
  database:
    image: 'mongo'
    container_name: 'my-mongo-container'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: dockerfile
    image: pranaysinghdev/user-service:latest
    networks: [tests-network]
    ports:
      - 5000:5000
    env_file:
      - compose.env
  product-service:
    container_name: product-service
    build:
      context: ./user-service
      dockerfile: dockerfile
    image: pranaysinghdev/product-service:latest
    networks: [tests-network]
    ports:
      - 5001:5001
    env_file:
      - compose.env