apiVersion: apps/v1
kind: Deployment
metadata:
  name:product-app-deployment
spec:
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: product-app
        image: docker.io/pranaysinghdev/product-service
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: product-app-service
spec:
  type: LoadBalancer
  selector:
    app: product-app
  ports:
  - port: 5001
    targetPort: 5001