apiVersion: apps/v1
kind: Deployment
metadata:
  name:user-app-deployment
spec:
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: docker.io/pranaysinghdev/user-service
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  type: LoadBalancer
  selector:
    app: user-app
  ports:
  - port: 5000
    targetPort: 5000